parameters:
    crop_image_type_class: 'Marrouchi\UploadCropImageBundle\Form\Type\CropType'
services:
    crop_image_bundle.image_type:
        class: %crop_image_type_class%
        tags:
            - { name: form.type, alias: crop_image }